# Generated by Django 4.2.13 on 2024-06-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="year_left",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="year_started",
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
    ]
