# Generated by Django 4.2.13 on 2024-06-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talent", "0002_employee_position_employee_year_left_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="year_started",
            field=models.IntegerField(default=2023),
        ),
    ]
