# Generated by Django 3.2.20 on 2024-06-30 11:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_of_reg',
            field=models.DateField(default=datetime.datetime(2024, 6, 30, 11, 13, 40, 565773, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=encrypted_model_fields.fields.EncryptedEmailField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_num',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2024, 6, 30, 11, 13, 40, 565773, tzinfo=utc)),
        ),
    ]
