# Generated by Django 3.2.20 on 2024-06-30 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_auto_20240630_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_of_reg',
            field=models.DateField(default=datetime.datetime(2024, 6, 30, 12, 58, 4, 60115, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='role',
            name='date_started',
            field=models.DateField(default=datetime.datetime(2024, 6, 30, 12, 58, 4, 75746, tzinfo=utc)),
        ),
    ]
