# Generated by Django 4.2.13 on 2024-06-28 06:48

import datetime
from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):
    dependencies = [
        ("talent", "0002_alter_company_date_of_reg_alter_role_date_started"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="date_of_reg",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 6, 28, 6, 48, 7, 287379, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=encrypted_model_fields.fields.EncryptedEmailField(),
        ),
        migrations.AlterField(
            model_name="employee",
            name="id_num",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="date_started",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 6, 28, 6, 48, 7, 291880, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
