# Generated by Django 4.2.13 on 2024-07-13 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("talent", "0003_auto_20240630_1458"),
        ("talent", "0004_alter_company_date_of_reg_alter_role_date_started"),
    ]

    operations = []
