# Generated by Django 4.2.13 on 2024-07-13 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talent", "0005_merge_20240713_1609"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="date_of_reg",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 13, 14, 9, 19, 784503, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="date_started",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 13, 14, 9, 19, 784503, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
